version: '2.1'

services:

  mongo:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017 # expose ports - HOST:CONTAINER
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null
  mongo-seed:
    build: ./seed
    environment:
      - DATABASE_NAME=something
      - COLLECTION_NAME=users
    links:
      - mongo
    depends_on:
      - mongo
